# Generated by Django 5.1.6 on 2025-06-07 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomes',
            name='user',
        ),
    ]
