# Generated by Django 5.1.6 on 2025-06-07 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='date',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='user',
        ),
    ]
